### ISSUE TITLE
value2 set to NaN when using PUT to update node

### ISSUE THREAD

**Issue by fogsag** [signalpoint/date#11]
I have a date field with start and end date. It is no problem to create a new node but as soon as i edit an existing node the value2 / enddate is not correct (null / NaN). Here the Log:

```
GET: http://example.com/?q=drupalgap/node/82.json jdrupal-7.x-1.3.min.js:30
200 - OK jdrupal-7.x-1.3.min.js:31
WARNING: theme_undefined() does not exist. Called by: drupalgap_render_page(). drupalgap-7.x-1.2.min.js:173
GET: http://example.com/?q=drupalgap/node/82.json jdrupal-7.x-1.3.min.js:30
200 - OK jdrupal-7.x-1.3.min.js:31
WARNING: drupalgap_entity_build_from_form_state - cannot use key (value) on field (field_angebotsdauer) language code array, key will be ignored. drupalgap-7.x-1.2.min.js:223
PUT: http://example.com/?q=drupalgap/node/82.json jdrupal-7.x-1.3.min.js:30
{"node":{"nid":"82","title":"test234","type":"inserat","language":"de","body":{"de":[{"value":"asdfasdf"}]},"field_angebotsdauer":{"de":[{"value":{"month":11,"day":13,"hour":9,"minute":"00","year":2015},"value2":{"month":null,"day":null,"hour":null,"minute":"NaN","year":null}}]},"field_bilder":{"de":[{"fid":""}]},"field_kontaktdaten":{"de":[{"target_id":"... (75)"}]}}} jdrupal-7.x-1.3.min.js:33
PUT http://example.com/?q=drupalgap/node/82.json 406 (Not Acceptable : Es wurde eine nicht erlaubte Auswahl entdeckt. Wenden Sie sich bitte an den Administrator der Website. Die Werteingabe fÃ¼r das Feld Angebotsdauer Enddatum ist ungÃ¼ltig:The day is missing.The month is missing.The year is missing.) 
```

This is in chromium browser. (With Firefox there are more and other problems.)

Thanks for this module!

**Comment by signalpoint** [comment]
@fogsag It looks like the DG date module is having a hard time understanding the value2 of a date field, perhaps because your site has a `de` language code. I'd recommend looking into the `date_assemble_form_state_into_field()` function, and stepping through it to try and identify where/when the function fails.

From your JSON, it looks like something fails when it tries to process the "minute":

```
"value2":{"month":null,"day":null,"hour":null,"minute":"NaN","year":null}
```

**Comment by fogsag** [comment]
Thank you.
form_state_value is not correct on the edit-form:
2015-11-23 20:30:00
should be like on create page (or when re-entering the to-date):
2015-11-23 20:30:00|2015-11-29 04:00:57

HTML Edit Form:
`<input id="edit-node-edit-field-angebotsdauer-de-0-value" value="2015-11-23 20:30:00" class="" type="hidden">`

HTML Add Form:
`<input id="edit-node-edit-field-angebotsdauer-de-0-value" value="2015-11-23 22:45:33|2015-11-23 22:45:33" class="" type="hidden">`

I have this problem also on another installation (language en)

**Comment by pierpa68** [comment]
@signalpoint I had the same problem and it has nothing to do with foreign language.
The fact is that the value of the hidden component of the date field on the form is set, from the function `theme_hidden` to the item.value before it has been added to the `value2` containing the "to" date.

I managed to solve it but had to modify both `date_field_widget_form` (in date.js) and `_drupalgap_form_render_element` (in drupalgap.js)

If you like I can try to make a commit...

HTH

**Comment by signalpoint** [comment]
@pierpa68 Thank you for the follow up information, that would be very helpful if you could make a pull request, or share your code here.

**Comment by pierpa68** [comment]
@signalpoint Hi, I've just sent a pull request for the changes that make fields with start and end date working, at least for my app...
More I've added some `t()`around some costants strings.

HTH

**Comment by signalpoint** [comment]
@fogsag  @pierpa68 Thank you both for pointing me in the right direction regarding the `value2` and the hidden input missing for existing values. That was definitely a big problem. I've committed a fix (and some related fixes) for this, grab the latest date.js for the fix. Also, this required a small improvement to DrupalGap core, so be sure to update to the latest `bin/drupalgap.min.js` as well.
