### ISSUE TITLE
Date Form Errors on Save

### ISSUE THREAD

**Issue by mkinnan** [signalpoint/date#13]
Not sure if really a duplicate of https://github.com/signalpoint/date/issues/8 since 12 hour format is more of a feature request.

Can't save a node with a date field. Currently using all the latest versions of drupalgap, jdrupal, date, etc.

`{"form_errors":{"field_event_date][und][0][value][hour":"An illegal choice has been detected. Please contact the site administrator.", "field_event_date][und][0][value2][hour":"An illegal choice has been detected. Please contact the site administrator."}}`

for

**jdrupal.js:1562**

**Comment by signalpoint** [comment]
@mkinnan This was most likely due to the fact that you're widget was configured for 5 minute intervals, and the date.js did not understand how to round the minute accordingly. It now understands how to do that.

**Comment by mkinnan** [comment]
The issue remains regardless of whether or not I use 1 or 5 minute intervals.

I am getting watchdog errors:
`Illegal choice 16 in Hour element.`

**Comment by mkinnan** [comment]
Errors seem to only happen when PM is selected. Dates with AM appear to work fine. I am getting 24 hour Illegal choice errors in watchdog in logs. So, if I select 2:00pm, I get a watchdog error of 

`Illegal choice 14 in Hour element.`

**Comment by signalpoint** [comment]
@mkinnan I've fixed this bug with this commit: https://github.com/signalpoint/date/commit/f59cee485f5f32f18288cd18986354abf3c86296

**Comment by mkinnan** [comment]
Editing and resaving the node without changing anything triggers this error again ...

![edit-2](https://cloud.githubusercontent.com/assets/13283396/14035068/14db4ba4-f1e7-11e5-86ae-6e28e251f214.PNG)
