### ISSUE TITLE
Changed Date Values not Saved with Editing Nodes

### ISSUE THREAD

**Issue by mkinnan** [signalpoint/date#16]
Upon editing the date/time of a node and then resaving the node, the cache is not being cleared to reflect the updated date/time.

**Comment by signalpoint** [comment]
@mkinnan Which cache do you mean?

**Comment by mkinnan** [comment]
I'm not sure it is a cache issue anymore. When i edit a node and change the date/time, it doesn't appear to change the date after saving and seeing the displayed date/time. I think this issue might be related to the other issues.

**Comment by mkinnan** [comment]
Tested the lasted snapshot of date module with the changes today. This is still an issue. When editing a date and changing the hours/minutes/day/month/etc, the changes aren't saved.

**Comment by signalpoint** [comment]
@mkinnan Bummer. I'll still need more specifics on this though, I don't know what you mean by the "changes aren't saved". It's important to be watching the console log during these events, keep an eye on your date field(s) JSON data, this helps put things in great context. A step by step approach to reproducing the bug is also crucial to properly solving this.

**Comment by mkinnan** [comment]
Here is the displayed date of a node:
![date-1](https://cloud.githubusercontent.com/assets/13283396/14448243/11ecf5be-0024-11e6-9eaf-3c1714c52a6d.PNG)

here is when I go to edit the node:
![date-2](https://cloud.githubusercontent.com/assets/13283396/14448248/20e3c692-0024-11e6-9862-8584025c1d99.PNG)

here are the values I changed:
![date-3](https://cloud.githubusercontent.com/assets/13283396/14448250/26e0d0b2-0024-11e6-96c3-ae400410d546.PNG)

here is the displayed value after resaving:
![date-1](https://cloud.githubusercontent.com/assets/13283396/14448245/1c48f094-0024-11e6-80ce-62d98c59a24e.PNG)

here is when I go back to edit the node again:
![date-2](https://cloud.githubusercontent.com/assets/13283396/14448253/2ccfd6da-0024-11e6-8379-af3b261a1f2a.PNG)

**Comment by signalpoint** [comment]
@mkinnan I didn't test this until after I fixed #21 , but I am not able to reproduce it. I do the exact same as your screen shots above, and things are updated properly when viewing/editing the node in web-app mode.

**Comment by mkinnan** [comment]
When enabling the Date Repeat Entity module, I have the issue with the date fields not being updated. Disabling the module and the date fields update just fine. There are no error messages that I can see.

Thoughts on how to debug?

Date Repeat Entity module:
https://www.drupal.org/project/date_repeat_entity

**Comment by mkinnan** [comment]
When I view the node JSON
http://example.com/?q=drupalgap/node/1642.json

Date Repate Entity Enabled
`{"vid":"1642","uid":"89","title":"Test","log":"","status":"1","comment":"2","promote":"0","sticky":"0","vuuid":"36447daf-73ab-41c3-a986-995344a3da3d","nid":"1642","type":"event","language":"und","created":"1461441769","changed":"1461443363","tnid":"0","translate":"0","uuid":"36447daf-73ab-41c3-a986-995344a3da3d","revision_timestamp":"1461443363","revision_uid":"89","field_event_registration":[],"field_event_date":{"und":[{"value":"2016-04-24 17:35:00","value2":"2016-04-24 21:15:00","rrule":null,"timezone":"UTC","timezone_db":"UTC","date_type":"datetime"}]},"field_facebook_event":[],"field_tags_event_type":{"und":[{"target_id":"14","name":"Cruise","entity_type":"taxonomy_term","bundle":null}]},"field_event_website":[],"body":{"und":[{"value":"asgdfghfd","summary":"","format":"filtered_html","safe_value":"<p>asgdfghfd</p>\n","safe_summary":""}]},"field_the_event_address":{"und":[{"country":"US","administrative_area":"AL","sub_administrative_area":null,"locality":"Albuquerque","dependent_locality":"","postal_code":"87123","thoroughfare":"123 Super Cool Road","premise":"","sub_premise":null,"organisation_name":null,"name_line":null,"first_name":null,"last_name":null,"data":null}]},"field_google_maps":{"und":[{"url":"http://maps.google.com/?q=123+Super+Cool+Road++Albuquerque+AL+87123","title":"Google Maps URL","attributes":[]}]},"og_group_ref":{"und":[{"target_id":"982","title":"1 A Test Group","entity_type":"node","bundle":null}]},"field_tags_event_location":{"und":[{"tid":"21831","name":"Albuquerque"},{"tid":"22093","name":"Alabama"}]},"path":"http://example.com/event/test","cid":"0","last_comment_timestamp":"1461441769","last_comment_name":null,"last_comment_uid":"89","comment_count":"0","name":"webmaster","picture":"7","data":"a:1:{s:7:\"contact\";i:1;}"}`

Date Repate Entity NOT Enabled:

`{"vid":"1642","uid":"89","title":"Test","log":"","status":"1","comment":"2","promote":"0","sticky":"0","vuuid":"36447daf-73ab-41c3-a986-995344a3da3d","nid":"1642","type":"event","language":"und","created":"1461441769","changed":"1461443363","tnid":"0","translate":"0","uuid":"36447daf-73ab-41c3-a986-995344a3da3d","revision_timestamp":"1461443363","revision_uid":"89","date_repeat_entity_clone_state":{"und":[{"value":"0"}]},"field_event_registration":[],"field_facebook_event":[],"field_event_website":[],"field_the_event_address":{"und":[{"country":"US","administrative_area":"AL","sub_administrative_area":null,"locality":"Albuquerque","dependent_locality":"","postal_code":"87123","thoroughfare":"123 Super Cool Road","premise":"","sub_premise":null,"organisation_name":null,"name_line":null,"first_name":null,"last_name":null,"data":null}]},"body":{"und":[{"value":"asgdfghfd","summary":"","format":"filtered_html","safe_value":"<p>asgdfghfd</p>\n","safe_summary":""}]},"field_event_date":{"und":[{"value":"2016-04-24 17:35:00","value2":"2016-04-24 21:15:00","rrule":null,"timezone":"UTC","timezone_db":"UTC","date_type":"datetime"}]},"field_google_maps":{"und":[{"url":"http://maps.google.com/?q=123+Super+Cool+Road++Albuquerque+AL+87123","title":"Google Maps URL","attributes":[]}]},"field_tags_event_type":{"und":[{"target_id":"14","name":"Cruise","entity_type":"taxonomy_term","bundle":null}]},"og_group_ref":{"und":[{"target_id":"982","title":"1 A Test Group","entity_type":"node","bundle":null}]},"field_tags_event_location":{"und":[{"tid":"21831","name":"Albuquerque"},{"tid":"22093","name":"Alabama"}]},"date_repeat_entity_master_uuid":{"und":[{"value":"36447daf-73ab-41c3-a986-995344a3da3d","format":null,"safe_value":"36447daf-73ab-41c3-a986-995344a3da3d"}]},"path":"http://example.com/event/test","cid":"0","last_comment_timestamp":"1461441769","last_comment_name":null,"last_comment_uid":"89","comment_count":"0","name":"webmaster","picture":"7","data":"a:1:{s:7:\"contact\";i:1;}"}`

**Comment by mkinnan** [comment]
When the Date Repeat Entity module is **not** enabled, the node JSON has this extra code:

```
{
   "date_repeat_entity_clone_state":{
      "und":[
         {
            "value":"0"
         }
      ]
   },
   "date_repeat_entity_master_uuid":{
      "und":[
         {
            "value":"36447daf-73ab-41c3-a986-995344a3da3d",
            "format":null,
            "safe_value":"36447daf-73ab-41c3-a986-995344a3da3d"
         }
      ]
   },
}
```

**Comment by mkinnan** [comment]
There is this error, but it is related to the date module and exists whether or not the Date Repeat Entity module is enabled. It only triggers when nodes are created/edited through Drupalgap.

`Location:  http://example.com/?q=drupalgap/node/1640.json`

`Notice: Undefined index: rrule in date_repeat_field_widget_validate() (line 336 of /var/www/html/sites/all/modules/date/date_repeat_field/date_repeat_field.module).`

**Comment by mkinnan** [comment]
It appears that the underlying issue is caused by **Date Repeat Field** submodule of the **Date** module which then trickles to Date Repeat Entity module. It appears the _rrule_ element is not being included in the drupalgap stuff.

**Comment by signalpoint** [comment]
@mkinnan Thank you for the thorough debug information on this. That's odd that that new date JSON shows up when the module is _not_ enabled. Can you find an example value of the `rrule` value anywhere in Drupal, maybe buried in the database or in the field config? I can see in the JSON that the value is `null` on your GET examples above, so perhaps if we set the `rrule` value in DrupalGap before POST/PUT on a node, that'll fix it. If you can find the correct value to use, then you could use this hook to get it into the data: http://api.drupalgap.org/7/global.html#hook_services_preprocess

**Comment by mkinnan** [comment]
@signalpoint It is weird behavior. And the example JSON code above is for a node that _does not_ have a repeat rule! I agree that somewhere a `null` probably needs to be inserted. I wonder if the JSON above (pasted below here) must be amended to the node JSON:

```
{
   "date_repeat_entity_clone_state":{
      "und":[
         {
            "value":"0"
         }
      ]
   },
   "date_repeat_entity_master_uuid":{
      "und":[
         {
            "value":"36447daf-73ab-41c3-a986-995344a3da3d",
            "format":null,
            "safe_value":"36447daf-73ab-41c3-a986-995344a3da3d"
         }
      ]
   },
}
```

Add I attached a screenshot of a table with a date field.

![field_data_field_event_date](https://cloud.githubusercontent.com/assets/13283396/14837461/d9c29d16-0bd5-11e6-8155-dcefec7623d1.PNG)

**Comment by signalpoint** [comment]
FYI, #22 was related to @mkinnan's issues here.
