### ISSUE TITLE
No Date Field for New Nodes

### ISSUE THREAD

**Issue by mkinnan** [signalpoint/date#21]
Went to create a new node with date field, and there is no field:

![date-no-field](https://cloud.githubusercontent.com/assets/13283396/14448270/5aad1eaa-0024-11e6-975f-86eeb93ad664.PNG)

**Comment by signalpoint** [comment]
@mkinnan There is likely a console log warning message(s) in this case... please confirm, thanks.

**Comment by mkinnan** [comment]
@signalpoint Sorry ... forgot to include:

`options_field_widget_form - unknown widget type: entityreference`
`WARNING: date_field_widget_form() - unsupported default value 2: now`
`date_field_widget_form - TypeError: Cannot read property 'getHours' of null`

**Comment by mkinnan** [comment]
Excellent! How do i push the code from **src** directory to build the new **date.js**?

**Comment by signalpoint** [comment]
Navigate to the date directory, and then run the grunt command.
- Tyler (sent from mobile device)
